// <auto-generated />
using System;
using Coach.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Coach.Infrastructure.Migrations
{
    [DbContext(typeof(CoachDbContext))]
    [Migration("20260827195134_AddDueDateNudges")]
    partial class AddDueDateNudges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Coach.Domain.Entities.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("Coach.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoachSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("CoachSlug", "CreatedAtUtc");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Coach.Domain.Entities.Coach", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Slug");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            Slug = "career",
                            DisplayName = "Career Coach"
                        },
                        new
                        {
                            Slug = "health",
                            DisplayName = "Health Coach"
                        },
                        new
                        {
                            Slug = "relationships",
                            DisplayName = "Relationships Coach"
                        },
                        new
                        {
                            Slug = "kids",
                            DisplayName = "Kids Coach"
                        });
                });

            modelBuilder.Entity("Coach.Domain.Entities.DueDateNudge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionItemId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDateAtNudge")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NudgeDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionItemId", "NudgeDate")
                        .IsUnique();

                    b.ToTable("DueDateNudges");
                });

            modelBuilder.Entity("Coach.Domain.Entities.GarminActivitySummary", b =>
                {
                    b.Property<long>("ActivityId")
                        .HasColumnType("bigint");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("Calories")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("integer");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActivityId");

                    b.HasIndex("Date");

                    b.ToTable("GarminActivitySummaries");
                });

            modelBuilder.Entity("Coach.Domain.Entities.GarminDailyMetric", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("AverageStressLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("AwakeMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryCharged")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryDrained")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryHigh")
                        .HasColumnType("integer");

                    b.Property<int?>("BodyBatteryLow")
                        .HasColumnType("integer");

                    b.Property<int?>("DeepSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LightSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxStressLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("ModerateIntensityMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("RemSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("RestingHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<int?>("SleepScore")
                        .HasColumnType("integer");

                    b.Property<int?>("StepGoal")
                        .HasColumnType("integer");

                    b.Property<int?>("Steps")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalSleepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("VigorousIntensityMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Date");

                    b.ToTable("GarminDailyMetrics");
                });

            modelBuilder.Entity("Coach.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoachSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("CoachSlug");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Coach.Domain.Entities.Reflection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoachSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CoachSlug", "CreatedAtUtc");

                    b.ToTable("Reflections");
                });

            modelBuilder.Entity("Coach.Domain.Entities.ValuesProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ValuesProfiles");
                });

            modelBuilder.Entity("Coach.Domain.Entities.ActionItem", b =>
                {
                    b.HasOne("Coach.Domain.Entities.Goal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coach.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("Coach.Domain.Entities.Coach", null)
                        .WithMany()
                        .HasForeignKey("CoachSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coach.Domain.Entities.DueDateNudge", b =>
                {
                    b.HasOne("Coach.Domain.Entities.ActionItem", null)
                        .WithMany()
                        .HasForeignKey("ActionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coach.Domain.Entities.GarminActivitySummary", b =>
                {
                    b.HasOne("Coach.Domain.Entities.GarminDailyMetric", null)
                        .WithMany()
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coach.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Coach.Domain.Entities.Coach", null)
                        .WithMany()
                        .HasForeignKey("CoachSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coach.Domain.Entities.Reflection", b =>
                {
                    b.HasOne("Coach.Domain.Entities.Coach", null)
                        .WithMany()
                        .HasForeignKey("CoachSlug")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
