<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Coach.Application\Coach.Application.csproj" />
    <ProjectReference Include="..\Coach.Infrastructure\Coach.Infrastructure.csproj" />
    <ProjectReference Include="..\Coach.Infrastructure.GoogleCalendar\Coach.Infrastructure.GoogleCalendar.csproj" />
    <ProjectReference Include="..\Coach.Infrastructure.Sms\Coach.Infrastructure.Sms.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
